name: project_xor
channels:
  - conda-forge
dependencies:
  - python=3.10
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - pandas
  - tqdm
  - pip
  - pip:
    - tensorflow
