name: project_xor
channels:
  - conda-forge
dependencies:
  - numpy
  - scipy
  - matplotlib
  - seaborn
  - jupyter
  - jupyterlab
  - jupyter_contrib_nbextensions
  - pandas
  - cudatoolkit
  - cudnn
  - pip
  - pip:
    - tensorflow
variables:
  LD_LIBRARY_PATH: $LD_LIBRARY_PATH:$CONDA_PREFIX/lib/
  